PREFIX cdt:    <http://w3id.org/awslabs/neptune/SPARQL-CDTs/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

ASK {
	BIND( cdt:Map(1, ?undef1) AS ?map1 )
	BIND( cdt:Map(1, ?undef2) AS ?map2 )

	BIND( ( ?map1 >= ?map2 ) AS ?result )

	FILTER( BOUND(?result) )
	FILTER( ?result = true )
}
