PREFIX cdt:    <http://example.org/cdt/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

ASK {
	BIND( ( "{1:42}"^^cdt:Map >= "{2:42}"^^cdt:Map ) AS ?result )
	FILTER( BOUND(?result) )
	FILTER( ?result = false )
}
