PREFIX cdt:    <http://example.org/cdt/>

ASK {
	BIND("{'hello'@en:'there'@en, 1:'one', 2:'two'}"^^cdt:Map AS ?mapIn )
	BIND( cdt:remove(?mapIn, 'hello') AS ?mapOut )

	FILTER( BOUND(?mapOut) )    # check that there was no error
	FILTER( ?mapOut = ?mapIn )
}
