PREFIX cdt:    <http://example.org/cdt/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
# list with two mixed types
ASK {
	BIND("['a', 1]"^^cdt:List AS ?list)
	FILTER(cdt:get(?list, 0) = 'a')
	FILTER(cdt:get(?list, 1) = 1)
}