PREFIX cdt:    <http://example.org/cdt/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
# list with two strings
ASK {
	BIND("['a', 'b']"^^cdt:List AS ?list)
	FILTER(cdt:get(?list, 0) = 'a')
	FILTER(cdt:get(?list, 1) = 'b')
}