PREFIX cdt:    <http://example.org/cdt/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

ASK {
	BIND( cdt:List(false) AS ?list1 )
	BIND( cdt:List(1) AS ?list2 )
	BIND( ( ?list1 < ?list2 ) AS ?result )
	FILTER( ! BOUND(?result) )
}
