PREFIX cdt:    <http://example.org/cdt/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

ASK {
        BIND( BNODE() AS ?x )
        BIND( ( cdt:List(?x) <= cdt:List(?x) ) AS ?result )
	FILTER( ! BOUND(?result) )
}
