PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
PREFIX cdt:    <http://example.org/cdt/>

# 1-entry map
ASK {
	BIND("{1: 'one'}"^^cdt:Map AS ?map)
	FILTER(cdt:contains(?map, 1))
	FILTER(!cdt:contains(?map, "02"^^xsd:integer))
}
