PREFIX cdt:    <http://example.org/cdt/>

# 2-entry map
ASK {
	BIND("{1: 'one', 2: 'two'}"^^cdt:Map AS ?map)
	FILTER(cdt:contains(?map, 1))
	FILTER(cdt:contains(?map, 2))

	FILTER(!cdt:contains(?map, 'one'))
	FILTER(!cdt:contains(?map, 'two'))
}