PREFIX cdt:    <http://example.org/cdt/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
# list with mixed defined and undefined types
ASK {
	BIND("[null, 2]"^^cdt:List AS ?list)
	FILTER(cdt:reverse(?list) = "[2,null]"^^cdt:List)
}