PREFIX cdt:    <http://example.org/cdt/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
# list with nested empty list
ASK {
	BIND("[[]]"^^cdt:List AS ?list)
	FILTER(cdt:tail(?list) = "[]"^^cdt:List)
}