PREFIX cdt:    <http://example.org/cdt/>


# concat identity (lhs)
ASK {
	BIND("[]"^^cdt:List AS ?empty)
	BIND("[1]"^^cdt:List AS ?one)
	BIND(cdt:concat(?empty, ?one) AS ?result)
	FILTER(?result = ?one)
}