PREFIX cdt:    <http://example.org/cdt/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

ASK {
	BIND( ( "[2]"^^cdt:List <= "[1]"^^cdt:List ) AS ?result )
	FILTER( BOUND(?result) )
	FILTER( ?result = false )
}
